Pull request for task #6
ruslanrix/movieparser pull request #2
Opened 2016-12-05 17:25 UTC by ruslanrix

2016-12-18 16:49 UTC, ruslanrix commented
1) Наследование нужно для повторного использования кода, когда подкласс может иметь доступ к методам родительского класса, а также изменять или дополнять их. Наследование позволяет избежать дублирование кода.
2) Да, заново определить методы родителя в наследниках можно. Использовать также и родительский метод в наследниках можно с помощью метода alias_method.
3) Модуль не может иметь подклассы и создавать экземпляры. Наследование следует применять, если это описание объекта. Модуль, если это свойство объекта.
4) **include** — добавляет методы модуля объекту. А **extend** — вызывает include для синглтон-класса объекта.

2016-12-19 21:53 UTC, zverok requested changes

2016-12-19 21:53 UTC, zverok commented on movie_class.rb
> +    attr_reader :row
что делает эта строчка?

2016-12-19 21:53 UTC, zverok commented on movie_class.rb
> +  end
что ето???

2016-12-19 21:53 UTC, zverok commented on movie_modules.rb
> +очень старый фильм (#{r_m.year} год), IMDB рейтинг: #{r_m.rating}"
почему такой странный перенос?.. этот код же прочитать невозможно

2016-12-19 21:53 UTC, zverok commented on movie_modules.rb
> +  end
зачем используется?

2016-12-19 21:53 UTC, zverok commented on movie_modules.rb
> +module MovieCommonMethods
Какая-то странная история с модулями произошла. В чём физический смысл вынести все методы в модули, оставив классы пустыми? В задании этого не было, и в жизни неясно зачем.

2016-12-22 15:07 UTC, ruslanrix commented on movie_class.rb
> +    attr_reader :row
забыл исправить этот момент)

2016-12-22 15:08 UTC, ruslanrix commented on movie_class.rb
> +  end
Исправил, хотя наверное eval не лучший вариант

2016-12-22 15:09 UTC, ruslanrix commented
По остальным моментам тоже исправил

2016-12-22 21:36 UTC, zverok requested changes

2016-12-22 21:36 UTC, zverok commented on movie_class.rb
> +    @class_name = case row[:year].to_i
Зачем `@`? В чём смысл?

2016-12-22 21:36 UTC, zverok commented on movie_class.rb
> +  .each{ |klass| eval "class #{klass} < Movie; end"}
Зачем? Почему просто не посоздавать честные классы?

2016-12-22 21:36 UTC, zverok commented on mymovielist_class.rb
> +    end
Нет, разное поведение для разных классов должно в самих быть определено. Иначе в чём смысл заводить разные классы-то?

2016-12-22 21:36 UTC, zverok commented on movie_modules.rb
> +  def class_rate(class_name, class_rating)
Нет, оно должно быть в классе определено.

2016-12-22 21:36 UTC, zverok commented on movie_modules.rb
> +      @mymovielist[watched_movie] = {}
Получается, этот модуль требует, чтобы класс уже имел такую переменную? Нехорошо.

2016-12-25 18:46 UTC, ruslanrix commented on movie_modules.rb
> +      @mymovielist[watched_movie] = {}
Вот этот момент недопонял. Это речь про watched_movie?

2016-12-25 18:49 UTC, ruslanrix commented
А вот нижеперечисленные методы, я предполагаю, следует перенсти в модуль? 

```
def all_directors
    @movielist.sort_by(&:director).uniq(&:director).map(&:director)
  end

  def stat_except_country (country)
    @movielist.reject{ |m| m.country.include? country }.length
  end

  def stat_country (country)
    @movielist.map{ |m| m.country.include? country }.length
  end

  def director_stats
    @movielist.group_by(&:director)
      .map{ |m, sum| [m, sum.length] }
      .to_h
  end

  def actor_stats
    @movielist.map{ |m| m.actors.split(',') }
      .flatten
      .reduce(Hash.new(0)){ |m, sum| m[sum] += 1; m }
  end
```

2016-12-26 13:54 UTC, zverok requested changes

2016-12-26 13:54 UTC, zverok commented on mymovielist_class.rb
> +  def class_rate(class_name, class_rating)
а зачем так, если классы сами могут за это отвечать?
```ruby
class AncientMovie
  RATE = 9.3
end
```
и всё.

2016-12-26 13:54 UTC, zverok commented on mymovielist_class.rb
> +  def rate(watched_movie, user_rating, watched_date)
А как же «вынести _всё_ занимающееся рейтингом, в отдельный модуль»?

2016-12-28 14:38 UTC, zverok approved these changes

2017-01-08 07:13 UTC, merged